### ISSUE TITLE
light_topswitch.wav in 48000Hz instead of 44100Hz

### ISSUE THREAD

**Issue by sndirsch** [rsimai/sounds#1]
Very cool sounds! All sounds are in 44.1kHz, only `light_topswitch.wav` is not. Could you recode light_topswitch.wav (48000 Hz) to 44100 Hz, please? E.g. via `sox light_topswitch.wav -b 16 -c 2 -r 44100 tmp.wav && mv tmp.wav topswitch.wav`

**Comment by rsimai** [comment]
recoded and pushed, thanks a lot!
